# Simple package

name: Spanish Accent 
parent: default

matches:
  - trigger: "n'"
    replace: "ñ"
  - trigger: "N'"
    replace: "Ñ"
  - trigger: "a'"
    replace: "á"
  - trigger: "e'"
    replace: "é"
  - trigger: "i'"
    replace: "í"
  - trigger: "o'"
    replace: "ó"
  - trigger: "u'"
    replace: "ú"
  - trigger: "A'"
    replace: "Á"
  - trigger: "E'"
    replace: "É"
  - trigger: "I'"
    replace: "Í"
  - trigger: "O'"
    replace: "Ó"
  - trigger: "U'"
    replace: "Ú"
  - trigger: "=+" # This is a special character that is not in the keyboard
    replace: "¿"
  - trigger: "~!" # This is a special character that is not in the keyboard
    replace: "¡"
  
